spring:
    config:
        activate:
            on-profile: test
hotel:
  msversion: 2301
  msenv: test
  msrelease: 23.01
  supportteam: QAteam
---
spring:
    config:
        activate:
            on-profile: prod
hotel:
  msversion: 2212
  msenv: Prod
  msrelease: 22.12
  supportteam: SmartOps
