
spring:
    config:
        activate:
            on-profile: test
user:
  msversion: 2301
  msenv: testUser
  msrelease: 23.01
  supportteam: QAteam
---
spring:
    config:
        activate:
            on-profile: prod
user:
  msversion: 2212
  msenv: ProdUser
  msrelease: 22.12
  supportteam: SmartOps
---
spring:
    config:
        activate:
            on-profile: dev  
  
user:
  msversion: 2302
  msenv: devUser
  msrelease: 23.02
  supportteam: dcut
