spring:
    config:
        activate:
            on-profile: test
hotel:
  registerOffice: delhi-test
  ceo: Ritesh Agarwal-test
---
spring:
    config:
        activate:
            on-profile: prod
hotel:
  registerOffice: delhi-prod
  ceo: Ritesh Agarwal-prod
